---
- hosts: localhost
  connection: local


  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansible-rg
        location: eastus
        
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: ansible-rg
        name: Demo-vNet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: ansible-rg
        name: webSubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: Demo-vNet
